/**
 * Premium UI tokens — 60% shell, 30% surfaces, 10% accent + semantic accents.
 * Single source of truth; `UI_COLORS` mirrors legacy flat keys for components.
 */
export const THEME = {
  shell: {
    bg: "#121417",
    bgElevated: "#1A1A1E",
    border: "#2D2D32",
    text: "#D1D5DB",
    textStrong: "#F9FAFB",
    textMuted: "#9CA3AF",
  },
  surface: {
    card: "#252529",
    cardMuted: "#1E1E22",
    elevated: "#2A2A2E",
    input: "#1E1E22",
    inputBorder: "#3F3F46",
  },
  text: {
    primary: "#F9FAFB",
    secondary: "#D1D5DB",
    muted: "#9CA3AF",
    onSheetLight: "#1F2937",
    onSheetDark: "#E8E8ED",
  },
  accent: {
    primary: "#8B5CF6",
    primaryHover: "#7C3AED",
    primaryBorder: "#A78BFA",
    primaryText: "#FFFFFF",
    subtleBg: "rgba(139, 92, 246, 0.22)",
  },
  warning: {
    stripe: "#FBBF24",
    text: "#FCD34D",
    border: "rgba(251, 191, 36, 0.38)",
    subtleBg: "rgba(251, 191, 36, 0.08)",
  },
  success: {
    text: "#34D399",
    border: "rgba(52, 211, 153, 0.42)",
    subtleBg: "rgba(52, 211, 153, 0.12)",
  },
  danger: {
    text: "#F87171",
    border: "rgba(248, 113, 113, 0.45)",
    subtleBg: "rgba(248, 113, 113, 0.1)",
  },
  /** Document canvas chrome (around the page), not app shell. */
  canvas: {
    workspaceLight: "#D4D0C8",
    workspaceLightWarm: "#DDDCD3",
    workspaceDark: "#141518",
    /** Off-white / parchment sheet */
    sheetLight: "#FAF6F0",
    sheetLightGradientEnd: "#F3EFE8",
    sheetDark: "#252529",
    sheetDarkElevated: "#2E2E34",
  },
} as const;

/** Flattened palette — prefer `THEME` for new code; keep keys stable for existing imports. */
export const UI_COLORS = {
  shellBg: THEME.shell.bg,
  shellBgElevated: THEME.shell.bgElevated,
  shellBorder: THEME.shell.border,
  shellText: THEME.shell.text,
  shellTextStrong: THEME.shell.textStrong,
  shellTextMuted: THEME.shell.textMuted,
  titleBarBg: THEME.shell.bg,
  statusBarBg: THEME.shell.bg,
  statusBarBorder: THEME.shell.border,
  accentPrimaryBg: THEME.accent.primary,
  accentPrimaryHover: THEME.accent.primaryHover,
  accentPrimaryBorder: THEME.accent.primaryBorder,
  accentPrimaryText: THEME.accent.primaryText,
  accentSubtleBg: THEME.accent.subtleBg,
  successText: THEME.success.text,
  successSubtleBg: THEME.success.subtleBg,
  dangerText: THEME.danger.text,
  storyPanel: {
    surface: THEME.shell.bgElevated,
    headerFrom: THEME.surface.cardMuted,
    headerTo: THEME.surface.card,
    border: THEME.shell.border,
    borderSoft: THEME.shell.border,
    textPrimary: THEME.text.primary,
    textSecondary: THEME.text.secondary,
    textMuted: THEME.text.muted,
    closeHover: THEME.surface.elevated,
    tabActiveBg: THEME.accent.subtleBg,
    tabActiveBorder: THEME.accent.primaryBorder,
    tabHoverBg: THEME.surface.elevated,
  },
  rightContext: {
    storyTabActiveBorder: THEME.accent.primaryBorder,
    storyTabActiveText: THEME.text.primary,
    storyTabActiveBg: THEME.accent.subtleBg,
    aiTabActiveBorder: THEME.accent.primaryBorder,
    aiTabActiveText: THEME.text.primary,
    aiTabActiveBg: THEME.accent.subtleBg,
    tabIdleText: THEME.shell.text,
    tabIdleHoverBg: THEME.surface.elevated,
  },
  navigator: {
    bg: THEME.shell.bg,
    text: THEME.shell.text,
    border: THEME.shell.border,
    borderSoft: THEME.shell.border,
    cardBorder: THEME.shell.border,
    cardBg: THEME.surface.cardMuted,
    cardHover: THEME.surface.elevated,
    sceneActive: THEME.accent.subtleBg,
    sceneHover: THEME.surface.elevated,
  },
  ribbon: {
    tabsBg: THEME.shell.bg,
    tabsBorder: THEME.shell.border,
    tabsTextMuted: THEME.text.muted,
    tabIdleText: THEME.shell.text,
    tabIdleHoverBg: THEME.surface.elevated,
    tabActiveBg: THEME.surface.cardMuted,
    tabActiveText: THEME.text.primary,
    tabActiveBorder: THEME.accent.primaryBorder,
    tabActiveGlow: "rgba(167, 139, 250, 0.24)",
    panelBg: THEME.surface.card,
    panelInnerBg: "rgba(255, 255, 255, 0.02)",
    panelBorder: THEME.shell.border,
    panelLabel: THEME.text.muted,
    controlBg: "rgba(255, 255, 255, 0.02)",
    controlBorder: "rgba(255, 255, 255, 0.08)",
    controlActiveBg: THEME.accent.subtleBg,
    controlActiveBorder: THEME.accent.primaryBorder,
    controlText: THEME.text.secondary,
    controlTextMuted: THEME.text.muted,
    controlHover: THEME.surface.elevated,
    separator: THEME.shell.border,
  },
} as const;
